### ISSUE TITLE
Validating UnityEvents wrapped in class inside component

### ISSUE THREAD

**Issue by Kordeyrow** [DarrenTsung/DTValidator#14]
Hello,
I have a component that has a class inside. This class has a UnityEvent and I think this event is not being validated because it's 'wrapped' inside the class.
What should I do?
Thank you!
![BoolVariableListener](https://user-images.githubusercontent.com/23510135/94632345-a1f2d100-02a0-11eb-8b42-ce5d8f4ce6d8.png)

**Comment by DarrenTsung** [comment]
Can you try the changes in the commit above? I think it should fix your problem: https://github.com/DarrenTsung/DTValidator/commit/5b15c1036374865039cb370ebf49c12fc8d5eff3

**Comment by Kordeyrow** [comment]
Looks like it's fixed!
I as on my way to try and add a "depth validation" but looks like you got the job done.
![image](https://user-images.githubusercontent.com/23510135/94718880-bf6b7d80-0328-11eb-8ce5-ed18b1941852.png)
I guess I didnt understand the code well ;p
Thank you! Good job!
PS: I was also adding a Toggle for checking Prefabs that are not on Resources folder.
PS2: I'm trying to use this Validator Project, because I am using ScriptableObjects Event System and I dont want to fail spotting changes in callbacks or registers that, in an C# event code would give me an reference error, but doesnt happen with inspector UnityEvents.

**Comment by Kordeyrow** [comment]
Another thing that I should note is that when the Validation happens inside the "wrapped classes" the Validation window doesnt show the Gameobject path and name.
![image](https://user-images.githubusercontent.com/23510135/94720623-18d4ac00-032b-11eb-8e51-1488da301f8e.png)

**Comment by Kordeyrow** [comment]
I found a way to add the path.
![image](https://user-images.githubusercontent.com/23510135/94744443-62cf8900-034f-11eb-9deb-120af0ee879b.png)
