### ISSUE TITLE
Importing repo cause lots of errors

### ISSUE THREAD

**Issue by Sami-AlEsh** [DarrenTsung/DTValidator#15]
when I tried to install this tool, I downloaded files and put them inside Assets\Plugins.
Then, lots of compilation errors happened.
I think this tool has dependencies like you should install other packages to work (ex: Unity TestFramework or NUnit,........) and there is no information about this!

**Comment by DarrenTsung** [comment]
Ah that's a good point, thanks for opening an issue. I'm not currently working with Unity or on this repository (although I think it may still be useful to people!), so I can't reproduce your issue. 

I'm open to any PRs updating the README to include any pre-requisite steps that are necessary!
