### ISSUE TITLE
Null Ref error when selecting missing script error in editor

### ISSUE THREAD

**Issue by Fl00f** [DarrenTsung/DTValidator#3]
Unity 2017.1.1f1

NullReferenceException: Object reference not set to an instance of an object
DTValidator.Internal.IValidationErrorExtensions+<SelectObjectInEditor>c__AnonStorey0.<>m__0 (UnityEngine.Object o) (at Assets/Plugins/DTValidator-master/Validation/Editor/ValidationErrors/IValidationErrorExtensions.cs:88)
System.Linq.Enumerable+<CreateWhereIterator>c__Iterator1D`1[UnityEngine.Object].MoveNext ()
DTValidator.Internal.IEnumerableGenericExtensions.FirstOrDefault[Object] (IEnumerable`1 enumerable, System.Predicate`1 predicate) (at Assets/Plugins/DTValidator-master/Core/Extensions/IEnumerableGenericExtensions.cs:10)
DTValidator.Internal.IValidationErrorExtensions.SelectObjectInEditor (IValidationError validationError) (at Assets/Plugins/DTValidator-master/Validation/Editor/ValidationErrors/IValidationErrorExtensions.cs:89)
DTValidator.Internal.IValidationErrorExtensions.SelectInEditor (IValidationError validationError) (at Assets/Plugins/DTValidator-master/Validation/Editor/ValidationErrors/IValidationErrorExtensions.cs:50)
DTValidator.ValidatorWindow.OnGUI () (at Assets/Plugins/DTValidator-master/Validation/Editor/ValidatorWindow.cs:123)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:272)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:265)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:232)

Also it would be nice to have some more information on objects with missing scripts other than just 
"Missing MonoScript!"

**Comment by DarrenTsung** [comment]
Thanks for reporting - pushed a fix. Was happening because the validation errors were returning GameObjects instead of Components as expected.

I also added the gameObject path to the information label! I went down the path of trying to figure out what the script Type was before remembering that because the guid is lost / missing Unity is unable to associate it with any Type..
