### ISSUE TITLE
DTValidator not detecting invalid serialized null field on serialized Serializable class instance inside of MonoBehviour.

### ISSUE THREAD

**Issue by YossiMH** [DarrenTsung/DTValidator#4]
Prefab `Prefab` contains MonoBehaviour `Component`.

`Component` contains private [SerializeField] `serializeableInnerClassInstance` which is an instance of [System.Serializable] class `InnerClass`  which is defined nested inside of class `OuterClass`.

`InnerClass` contains [SerializeField] `field`, which is set to None in the Unity Inspector.

DTValidator isn't catching the invalid null field `OuterClass.InnerClass.field`.

Thanks!

**Comment by DarrenTsung** [comment]
Hi, thanks for reporting this issue. I will probably not get to take a look at reproducing this issue till the weekend.

Feel free to take a look at the tests on the develop branch, seems fairly trivial to write a test for this specific case:
https://github.com/DarrenTsung/DTValidator/blob/develop/Tests/Editor/BasicGameObjectValidationTests.cs.
Would help :).

**Comment by DarrenTsung** [comment]
This should be fixed in the latest commit in `master`. There's a small issue that happens when this edge case is triggered which is that the ValidationError doesn't work with selecting the object in the scene, but should be fine.

**Comment by YossiMH** [comment]
@DarrenTsung Fast turnaround time!! Thanks!! :)
